### ENGINE ###
UPDATE_PERIOD_MS = 2
DRAW_PERIOD_MS = 15

### WINDOW ###
WINDOW_SIZE = (640, 480)

### GRAPHICS ###
SPRITE_PATH = "sprite/"

### ENTITIES ###
WORLD_DIM = (640, 480)

SPACESHIP_SPEED_PIXEL_PER_SECOND = 100
SPACESHIP_SPRITE_NAME = "spaceship.png"

MISSILE_RECT_DIM = (2, 6)
MISSILE_RECT_COLOR = (0, 255, 0)
MISSILE_SPEED_PIXEL_PER_SECOND = 500


ALIEN_FORMATION = [[1] * 11, [2] * 11, [2] * 11, [3] * 11, [3] * 11]
ALIEN_FORMATION_WIDTH = 360
ALIEN_FIRING_PERIOD_MS = 500
ALIEN_SPRITE_SHIFT_DELAY_MS = 500
ALIEN_SPEED_PIXEL_PER_SECOND = 5
ALIEN_SPRITE_NAMES = [
    ["alien1_frame1.png", "alien1_frame2.png"],
    ["alien2_frame1.png", "alien2_frame2.png"],
    ["alien3_frame1.png", "alien3_frame2.png"]
]

LASER_RECT_DIM = (2, 6)
LASER_RECT_COLOR = (255, 255, 0)
LASER_SPEED_PIXEL_PER_SECOND = 100
